services:
  xbrowsersync:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '39056:9056'
    volumes:
      - ./xbs_data:/data/xbs
    environment:
      XBROWSERSYNC_DB_SQLITE_PATH: '/data/xbs'
    networks:
      - xbs

networks:
  xbs:
